school/classroom/urls.py
from django.urls import path
from . import views

app_name = 'classroom'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('thank_you/', views.ThankYouView.as_view(), name = 'thankyou'),
    path('contact/', views.ContactFormView.as_view(), name = 'contact'),
    path('create_teacher/', views.TeacherCreateView.as_view(), name = 'createteacher'),
    path('list_teacher/', views.TeacherListView.as_view(), name='listteacher'),
    path('teacher_detail/<int:pk>/', views.TeacherDetailView.as_view(), name = 'teacherdetail'),
    path('update_teacher/<int:pk>/', views.TeacherUpdateView.as_view(), name = 'updateteacher'),
    path('delete_teacher/<int:pk>/', views.TeacherDeleteView.as_view(), name = 'deleteteacher')
]

school/school/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('classroom/', include('classroom.urls'))
]

school/classroom/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    first_name = models.CharField(max_length = 30)
    last_name = models.CharField(max_length=30)
    subject = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.first_name} {self.last_name} teaches {self.subject}."

school/classroom/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget= forms.Textarea)

school/classroom/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, FormView, CreateView, ListView, DetailView, UpdateView, DeleteView
from classroom.forms import ContactForm
from classroom.models import Teacher

# Create your views here.
class HomeView(TemplateView):
    template_name = 'classroom/home.html'

class ThankYouView(TemplateView):
    template_name = 'classroom/thank_you.html'

class ContactFormView(FormView):
    form_class = ContactForm
    template_name = 'classroom/contact.html'

    #SUCCESS URL
    #URL NOT A template.html
    success_url = reverse_lazy('classroom:thankyou')
    #success_url = '/classroom/thank_you/'

    #what to do with the form?
    #ContactForm(request.POST)
    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)

class TeacherCreateView(CreateView):
    model = Teacher
    fields = '__all__'
    success_url = reverse_lazy('classroom:thankyou')

class TeacherListView(ListView):
    model = Teacher
    context_object_name = 'teacher_list'
    #queryset = Teacher.objects.order_by('first_name').filter(subject = 'Django')

class TeacherDetailView(DetailView):
    model = Teacher

class TeacherUpdateView(UpdateView):
    model = Teacher
    fields = '__all__'
    success_url = reverse_lazy('classroom:listteacher')

class TeacherDeleteView(DeleteView):
    model = Teacher
    success_url = reverse_lazy('classroom:listteacher')

school/classroom/templates/classroom/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

school/classroom/templates/classroom/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome to Home.html</h1>
    <ul>
        <li><a href='{% url 'classroom:thankyou' %}'> Thank You Page </a></li>
        <li><a href='{% url 'classroom:contact' %}'> Contact Us Page </a></li>
        <li><a href='{% url 'classroom:createteacher' %}'> Create a New Teacher </a></li>
        <li><a href='{% url 'classroom:listteacher' %}'> List all the teachers </a></li>
    </ul>
</body>
</html>

school/classroom/templates/classroom/teacher_confirm_delete.html
<h1>Are you sure you want to delete this teacher</h1>
<h2>{{ teacher }} </h2>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete">
</form>

school/classroom/templates/classroom/teacher_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{teacher}}
</body>
</html>

school/classroom/templates/classroom/teacher_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

school/classroom/templates/classroom/teacher_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<h1>List of Teachers</h1>
<ul>
    {% for teacher in teacher_list %}
    <li>
        <a href="/classroom/teacher_detail/{{teacher.id}}">{{teacher.first_name}} {{teacher.last_name}}</a>
        <a href="/classroom/update_teacher/{{teacher.id}}">Update Teacher Info</a>
        <a href="/classroom/delete_teacher/{{teacher.id}}">Delete {{teacher.first_name}}</a>
    </li>
    {% endfor %}
</ul>
</body>
</html>

school/classroom/templates/classroom/thank_you.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Thank You!<h1>
    
</body>
</html>