car_listing_website/car_listing_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cars/', include('cars.urls')),
]

car_listing_website/cars/urls.py
from django.urls import path
from . import views

app_name='cars'

urlpatterns = [
    path('list/', views.list, name='list'),
    path('add/', views.add, name='add'),
    path('delete/', views.delete, name='delete')
]

car_listing_website/cars/models.py
from django.db import models

# Create your models here.
class Car(models.Model):
    Model = models.CharField(max_length=30)
    Brand = models.CharField(max_length=30)
    Year = models.IntegerField()

    def __str__(self):
        return f"{self.pk} : {self.Model} was made by {self.Brand} in {self.Year}."
    

car_listing_website/cars/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from . import models

# Create your views here.
def list(request):
    all_cars = models.Car.objects.all()
    context={'car_list' : all_cars}
    return render(request, 'cars/list.html', context=context)

def add(request):
    if request.POST:
        model = request.POST['model']
        brand = request.POST['brand']
        year = request.POST['year']
        models.Car.objects.create(Model=model, Brand=brand, Year=year)
        return redirect(reverse('cars:list'))
    else:
        return render(request, 'cars/add.html')

def delete(request):
    if request.POST:
        pkey = request.POST['pk']
        try:
            models.Car.objects.get(pk=pkey).delete()
            return redirect(reverse('cars:list'))
        except:
            print("Entered Primary Key not found.")
            return redirect(reverse('cars:list'))
    else:
        return render(request, 'cars/delete.html') 

car_listing_website/cars/templates/cars/add.html
{% extends 'base.html' %}

{% block content %}
<div class='container'>
<h1>ADD.HTML</h1>
<h2>Add a new car to the database.</h2>
<form action="" method="POST">
    {% csrf_token %}
    <div class='form-group'>
        <label for='model'>Model</label>
        <input class='form-control' type='text' name="model" id="model">
    </div>
    <div class='form-group'>
        <label for="brand">Brand</label>
        <input class='form-control' type="text" name="brand" id="brand">
    </div>
    <div class='form-group'>
        <label for="year">Year</label>
        <input class='form-control' type="number" name="year" id="year">
    </div>
    <input class='btn btn-primary' type="submit" value="Submit">
{% endblock %}

car_listing_website/cars/templates/cars/delete.html
{% extends 'base.html' %} {% block content %}
<h1>DELETE.HTML</h1>
<h2>Enter the Primary Key to delete it's corresponding entry.</h2>
<form action="" method="POST">
  {% csrf_token %}
  <div class="container">
    <label for="pk">Primar Key</label>
    <input class="form-control" type="number" id="pk" name="pk">
    <input class="btn btn-primary" type="submit" value="Delete Entry">
  </div>
</form>
{% endblock %}

car_listing_website/cars/templates/cars/list.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h1>LIST.HTML</h1>
  <ul>
    {% for car in car_list %}
    <li>{{car}}</li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

car_listing_website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <!-- NAVBAR -->
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNavAltMarkup"
          aria-controls="navbarNavAltMarkup"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link" href="{% url 'cars:list' %}">LIST</a>
            <a class="nav-link" href="{% url 'cars:add' %}">ADD</a>
            <a class="nav-link" href="{% url 'cars:delete' %}">DELETE</a>
          </div>
        </div>
      </div>
    </nav>
    {% block content %} {% endblock %}
  </body>
</html>