Library_Website/Library_Website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/')),
    path('accounts/', include('django.contrib.auth.urls'))
]

Library_Website/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name ='index'),
    path('create_book/', views.BookCreate.as_view(), name= 'create_book'),
    path('book/<int:pk>/', views.BookDetail.as_view(), name = 'book_detail'),
    path('my_view/', views.my_view, name = 'myview'),
    path('signup', views.SignupView.as_view(), name = 'signup'),
    path('profile/', views.CheckedOutBooksByUser.as_view(), name = 'profile')
]

Library_Website/catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User

# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length = 150)
    def __str__(self):
        return self.name

class Language(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name

class Author(models.Model):
    first_name = models.CharField(max_length = 200)
    last_name = models.CharField(max_length = 200)
    date_of_birth = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ['first_name', 'last_name']

    def get_absolute_url(self):
        return reverse("author_detail", kwargs={"pk": self.pk})
    
    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Book(models.Model):
    title = models.CharField(max_length = 200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null = True)
    summary = models.TextField(max_length = 600)
    isbn = models.CharField('ISBN', max_length = 13, unique =True)
    genre = models.ManyToManyField(Genre)
    language = models.ForeignKey("Language", on_delete=models.SET_NULL, null = True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("book_detail", kwargs={"pk": self.pk})
    
class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default = uuid.uuid4, editable = False)
    book = models.ForeignKey('Book', on_delete = models.RESTRICT)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null= True, blank = True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On Loan'),
        ('a', 'Available'),
        ('r', 'Reserved')
    )
    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default = 'm')

    class Meta:
        ordering = ['status', 'due_back']

    def __str__(self):
        return f'{self.id} : {self.book.title}'

Library_Website/catalog/views.py
from django.shortcuts import render
from .models import Author, Genre, Language, Book, BookInstance
from django.views.generic import CreateView, DetailView, ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

# Create your views here.
def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_avail = BookInstance.objects.filter(status__exact='a').count()

    context = {
        'num_books' : num_books,
        'num_instances' : num_instances,
        'num_instances_avail' : num_instances_avail
    }

    return render(request, 'catalog/index.html', context=context)

class BookCreate(LoginRequiredMixin, CreateView):
    model = Book
    fields = '__all__'

class BookDetail(DetailView):
    model = Book

@login_required
def my_view(request):
    return render(request, 'catalog/my_view.html')

class SignupView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'catalog/signup.html'

class CheckedOutBooksByUser(LoginRequiredMixin, ListView):
    model = BookInstance
    template_name = 'catalog/profile.html'
    paginate_by = 5 #5 Book instances per page

    def get_queryset(self) :
        return BookInstance.objects.filter(borrower=self.request.user)

Library_Website/catalog/templates/catalog/book_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Book Detail</h1>
    {{ book }}
</body>
</html>

Library_Website/catalog/templates/catalog/book_form.html
<h1>Create New Book</h1>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type='submit' value='CREATE'>
</form>

Library_Website/catalog/templates/catalog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>HOMEPAGE</h1>
    <p>Total Books : {{num_books}}</p>
    <p>Num Available : {{num_instances_avail}}</p>

    {% if user.is_authenticated %}
        <p>You are Logged In.</p>
        <p>Welcome : {{user.get_username}}</p>
        <a href="{% url 'logout' %}?next={{request.path}}">Logout</a>
    {% else %}
        <p>You are not logged in</p>
        <a href="{% url 'login' %}?next={{request.path}}">Login</a>
    {% endif %}
</body>
</html>

Library_Website/catalog/templates/catalog/my_view.html
<h1>LOGGED IN USERS ONLY</h1>

Library_Website/catalog/templates/catalog/profile.html
<h1>Welcome to your profile {{user.get_username}}</h1>
<h2>Here are your books checked out</h2>

{% for book in bookinstance_list %}
    <p>{{book}}</p>
{% endfor %}

Library_Website/catalog/templates/catalog/signup.html
<h1>Register New User Here</h1>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="SignUp">
</form>