new_site/my_app/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name ="my_app"

urlpatterns = [path("", views.simple_view, name="simple"),
               path("variable", views.variable_view, name="variable"),
               path("user1", views.user1_info, name="user1"),
               path("user2", views.user2_info, name="user2"),
               path("user_not_found", views.user_not_found, name="user_not_found"),
               path("Patients", views.Patient_list, name="Patients")
               ]

new_site/new_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("my_app/",include("my_app.urls"))
]

handler404 = 'new_site.views.my_custom_page_not_found_view'

new_site/my_app/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Patient(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    age = models.IntegerField()
    heartbeat = models.IntegerField(default= 60, validators=[MaxValueValidator(300, message="Heartbeat can't be greater than 300"), MinValueValidator(1, message="Heartbeat can't be smaller than 1")])

    def __str__(self):
        return f"{self.first_name} {self.last_name} of {self.age} age. {self.heartbeat}"

new_site/my_app/views.py
from django.shortcuts import render
from . import models
# Create your views here.


def simple_view(request):
    return render(request, "my_app/example.html")


my_var = {"first_name": "shAshWat", "last_name": "Singh",
          "sim_list": [1, 2, 3, 4], "sim_dict": {"inside_key1": "inside_value1", "inside_key2": "inside_value2"},
          "user_logged_in" : True, "vip_access" : True  }


user1 = {"first_name": "shAshWat", "last_name": "Singh", "age": 20, "gender": "Male", "premium_user":"Yes"}
user2 = {"first_name": "AYUsh", "last_name": "jiMMy", "age": 18, "gender": "Male", "premium_user":"No"}

def variable_view(request):
    return render(request, "my_app/variable.html", context=my_var)

def user1_info(request):
    return render(request, "my_app/user.html", context=user1)

def user2_info(request):
    return render(request, "my_app/user.html", context=user2)

def user_not_found(request):
    return render(request, "my_app/user_not_found.html")

def Patient_list(request):
    all_patients = models.Patient.objects.all()
    Patient_render = {"patients" : all_patients}
    return render(request, 'my_app/list.html', context=Patient_render)

new_site/new_site/views.py
from django.shortcuts import render

def my_custom_page_not_found_view(request, exception):
    return render(request, "error_view.html", status=404)

new_site/my_app/templates/my_app/example.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Example HTML Template Attached</h1>
    <h2>
        <a href="{% url 'my_app:variable' %}">Login Here</a>
        <br>
        {% load static %}
        <img src="{% static 'my_app/car.gif' %}" alt="Fucking Drifting">
        <br>
        <img src="{% static 'car2.jpg' %}" alt="Lambo" height=200 width=400> 
    </h2>
</body>
</html>

new_site/my_app/templates/my_app/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ul>
    {% for person in patients %}
    <li>{{person}}</li>
    {% endfor %}
    </ul>
</body>
</html>

new_site/my_app/templates/my_app/user.html
{% extends 'base.html' %}
{% block title %}User Info{% endblock title %}
{% block content %}
    <p>Information provided above is made available through the data present in the databases at the time of visiting the web page.
         Hence, it's variable and can change with respect to time.<p>
{% endblock content %}

new_site/my_app/templates/my_app/user_not_found.html
{% extends 'base.html' %}
{% block title %}User Not Found{% endblock title %}
{% block user_info %} <h1>User Not Found</h1> {% endblock user_info %}
{% block content %}
    <p>Information provided above is made available through the data present in the databases at the time of visiting the web page.
        No information for the provided user is found.<p>
{% endblock content %}

new_site/my_app/templates/my_app/variable.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>VARIABLE.HTML<h1>
    {% comment %} Filter Docs : https://docs.djangoproject.com/en/4.1/ref/templates/builtins/#built-in-filter-reference {% endcomment %}
    <h2>
        <ul>
            {% for num in sim_list %}
            <li>{{num}}</li>
            {%endfor%}
        </ul>
    </h2>
    <h3>
        <ol type=i>
            {% for key,value in sim_dict.items %}
            <li>{{key}} : {{value}}</li>
            {%endfor%}
    </h3>
    
    {% if user_logged_in and vip_access %}
        <h2>Welcome {{first_name | lower | capfirst}} {{last_name | lower | capfirst}}.</h2>
        <h3>You are logged in as a premium user and can enjoy all the features.</h3>
    {% elif user_logged_in %}
        <h2>Welcome {{first_name | lower | capfirst}} {{last_name | lower | capfirst}}.</h2>
        <h3>You are logged in.</h3>
    {% else %}
        <h2>Kindly Log in.</h2>
    {% endif %}
</body>
</html>

new_site/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}The Best Website{% endblock title %}</title>
</head>
<body>
    <h3><ul>
        {% block nav_bar %}
            <li><a href="home">Home</a></li>
            <li><a href="servics">Services</a></li>
            <li><a href="about">About</a></li>
        {% endblock nav_bar %}
    </ul></h3>
    {% block user_info %}
        <h1>User Information</h1>
        <h2>Name : {{first_name | lower | capfirst}} {{last_name | lower | capfirst}} <br>
            Age : {{age}} <br>
            Gender : {{gender}}<br>
            Premium User : {{premium_user}}
        </h2>
    {% endblock user_info %}
    {% block content %}{% endblock content %}
</body>
</html>

new_site/templates/error_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Error 404 : Page Not Found</h1>
</body>
</html>